/**
 * Acceptance test for ac-31 — B2 contradiction pass: before locking, run the
 * cross-answer consistency pass exactly once (not a fixpoint loop), produce a
 * conflict list whose entries are pointers into real answer records, feed the
 * list length — not a constant — into the A4 readiness floor as `conflicting`
 * so the floor actually gates the lock, and record a not-run honestly
 * (ADR-0018) so it is never disguised as a verified conflict count of 0.
 *
 * Frozen red: the modules under src/interview/consistency/ and
 * src/interview/readiness/ do not exist yet; the piece-3 implementation must
 * turn this file green without editing it.
 *
 * Oracle source: gate-a/rows/ac-31.json (oracle_statement clauses 1-6).
 * Every assertion runs on top of a test-injected deterministic judge. There is
 * exactly one lock entry point — `enterLockPath` — and both the pass-was-run
 * and the pass-was-not-run situations are observed through it (the not-run
 * situation is produced by calling the real lock path with no judge, never by
 * a test-only side door), so the honest not-run record must be generated by
 * the same code that generates the ran record.
 *
 * Contract surface fixed by this file:
 *   enterLockPath({ statement, answers, judge? })
 *     -> { locked, lock?, pass?, record: { consistency }, journal, refusal? }
 *   runContradictionPass({ answers, judge }) -> { id, conflicts }
 *   buildConflictList({ reports, answers }) -> entries
 *   deriveConflictingInput(passOrMarker) -> { status, conflicting? }
 *   evaluateConflictingFloor(input) -> { blocked, reason? }
 *
 * Residual — deliberately NOT tested here, per the row's residual declaration:
 * (a) contradiction-content judgment — whether two answers are actually
 *     semantically contradictory is an LLM/human call; the contract statement
 *     itself declares it residual, so the fixtures inject a deterministic
 *     judge and only the mechanical properties are closed;
 * (b) detection quality of the production judge (recall/precision — missed or
 *     spurious contradictions) — a structurally passing run with 0 detections
 *     is possible, so quality belongs to the separate retro/calibration loop
 *     (bundle 7), not this file;
 * (c) the remaining A4 readiness-floor inputs (unsure-answer count, demoted
 *     reviews, characterize verdicts) and the floor's overall completeness —
 *     those are ac-28's scope; this file closes only the `conflicting`
 *     component's substitution and effectuation.
 * No prose is graded.
 */

import { describe, expect, test } from "bun:test";
import { buildConflictList } from "../src/interview/consistency/conflict-list";
import {
  enterLockPath,
  runContradictionPass,
} from "../src/interview/consistency/contradiction-pass";
import {
  deriveConflictingInput,
  evaluateConflictingFloor,
} from "../src/interview/readiness/conflicting-input";

const ANSWER_TEXT_AUTO = "Yes, export the report automatically every night.";
const ANSWER_TEXT_CONFIRM = "No, never write any file without an explicit confirmation.";
const ANSWER_TEXT_STORE = "Store exports under the reports directory.";
const ANSWER_TEXT_KEEP = "Keep every export forever; never delete reports.";

type AnswerRecord = { id: string; question: string; answer: string };

const ANSWERS: ReadonlyArray<AnswerRecord> = [
  { id: "ans-1", question: "Should the export run automatically?", answer: ANSWER_TEXT_AUTO },
  {
    id: "ans-2",
    question: "May the tool write files without asking?",
    answer: ANSWER_TEXT_CONFIRM,
  },
  { id: "ans-3", question: "Where should exports be stored?", answer: ANSWER_TEXT_STORE },
  { id: "ans-4", question: "Should old exports be kept?", answer: ANSWER_TEXT_KEEP },
];

/** A materially different answer set, used to show pass ids are per-run values. */
const OTHER_ANSWERS: ReadonlyArray<AnswerRecord> = [
  {
    id: "oth-1",
    question: "Which timezone drives the schedule?",
    answer: "Use UTC for scheduling.",
  },
  { id: "oth-2", question: "Who receives the report?", answer: "Send it to the finance mailbox." },
];

const STATEMENT = "Nightly report exports are written only after explicit user confirmation.";

const PAIR_1_2 = { answer_ids: ["ans-1", "ans-2"] };
const PAIR_3_4 = { answer_ids: ["ans-3", "ans-4"] };
const PAIR_1_4 = { answer_ids: ["ans-1", "ans-4"] };

/**
 * Deterministic injected judge. The spy counts invocations and captures the
 * answer set it was handed, so a hidden convergence re-run cannot escape the
 * run count and the cross-answer property (the judge sees the whole set) is
 * itself checked rather than assumed.
 */
const makeSpyJudge = (reports: ReadonlyArray<{ answer_ids: string[] }>) => {
  const spy = { calls: 0, received: [] as ReadonlyArray<AnswerRecord>[] };
  const judge = (answers: ReadonlyArray<AnswerRecord>) => {
    spy.calls += 1;
    spy.received.push(answers);
    return reports.map((r) => ({ answer_ids: [...r.answer_ids] }));
  };
  return { judge, spy };
};

/** Own properties that could be called to mutate an outcome after the fact. */
const callableKeys = (value: unknown): string[] =>
  value !== null && typeof value === "object"
    ? Object.keys(value as Record<string, unknown>).filter(
        (k) => typeof (value as Record<string, unknown>)[k] === "function",
      )
    : [];

describe("ac-31 clause 1: entering the lock path runs the consistency pass exactly once (not fixpoint)", () => {
  test("with a conflict-reporting judge the pass runs once and no convergence re-run happens", () => {
    const { judge, spy } = makeSpyJudge([PAIR_1_2]);
    const outcome = enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge });

    // Execution record: exactly one pass-run entry, even though the judge
    // reported a conflict (a fixpoint loop would re-run until no change).
    const passEntries = outcome.journal.filter((e) => e.kind === "contradiction-pass");
    expect(passEntries).toHaveLength(1);
    // Behavioral backstop: the judge itself was consulted exactly once.
    expect(spy.calls).toBe(1);
    // The single run really carried the judge's report.
    expect(outcome.pass?.conflicts).toHaveLength(1);
  });

  test("with a clean judge the pass still runs exactly once", () => {
    const { judge, spy } = makeSpyJudge([]);
    const outcome = enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge });

    expect(outcome.journal.filter((e) => e.kind === "contradiction-pass")).toHaveLength(1);
    expect(spy.calls).toBe(1);
  });

  test("the single run hands the judge the whole answer set verbatim (cross-answer, not per-answer)", () => {
    const { judge, spy } = makeSpyJudge([]);
    enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge });

    expect(spy.received).toHaveLength(1);
    const seen = spy.received[0] ?? [];
    expect(seen.map((a) => a.id)).toEqual(["ans-1", "ans-2", "ans-3", "ans-4"]);
    expect(seen.map((a) => a.answer)).toEqual([
      ANSWER_TEXT_AUTO,
      ANSWER_TEXT_CONFIRM,
      ANSWER_TEXT_STORE,
      ANSWER_TEXT_KEEP,
    ]);
  });
});

describe("ac-31 clause 2: the pass precedes the lock and the lock references the pass result", () => {
  test("the pass execution record comes before the lock record and points at a real pass id", () => {
    const { judge } = makeSpyJudge([]);
    const outcome = enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge });
    expect(outcome.locked).toBe(true);

    const kinds = outcome.journal.map((e) => e.kind);
    const passIndex = kinds.indexOf("contradiction-pass");
    const lockIndex = kinds.indexOf("lock");
    expect(passIndex).toBeGreaterThanOrEqual(0);
    expect(lockIndex).toBeGreaterThan(passIndex);

    // The reference must be a real, non-empty identifier — not undefined on
    // both sides, which would make the equality vacuous.
    const passId = outcome.pass?.id;
    expect(typeof passId).toBe("string");
    expect((passId ?? "").length).toBeGreaterThan(0);
    expect(outcome.journal[passIndex]?.ref).toBe(passId);
  });

  test("the lock output references the pass result it was gated on, by a live per-run id", () => {
    const { judge } = makeSpyJudge([]);
    const first = enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge });
    const second = enterLockPath({
      statement: STATEMENT,
      answers: OTHER_ANSWERS,
      judge: makeSpyJudge([]).judge,
    });

    const firstId = first.pass?.id;
    const secondId = second.pass?.id;
    expect(typeof firstId).toBe("string");
    expect((firstId ?? "").length).toBeGreaterThan(0);
    expect(typeof secondId).toBe("string");
    expect((secondId ?? "").length).toBeGreaterThan(0);
    // Two different pass runs are distinguishable, so the reference identifies
    // one specific pass result rather than being a shared placeholder.
    expect(secondId).not.toBe(firstId);

    expect(first.lock?.pass_ref).toBe(firstId);
    expect(second.lock?.pass_ref).toBe(secondId);
  });

  test("no judge means no pass, no lock, and no after-the-fact way to reach a locked state", () => {
    // The pass is an input of the lock call itself. Reaching the lock path
    // without it yields a refusal whose outcome exposes no mutator, so a pass
    // executed later cannot retroactively satisfy the ordering clause.
    const outcome = enterLockPath({ statement: STATEMENT, answers: ANSWERS });
    expect(outcome.locked).toBe(false);
    expect(outcome.lock).toBeUndefined();
    expect(outcome.pass).toBeUndefined();
    expect(outcome.refusal?.reason).toBe("consistency-pass-not-run");
    expect(outcome.journal.some((e) => e.kind === "contradiction-pass")).toBe(false);
    expect(outcome.journal.some((e) => e.kind === "lock")).toBe(false);

    // Return-contract: the refusal is inert data — nothing on it (or on its
    // record) can be invoked to flip `locked` afterwards.
    expect(callableKeys(outcome)).toEqual([]);
    expect(callableKeys(outcome.record)).toEqual([]);
    expect(callableKeys(outcome.record?.consistency)).toEqual([]);

    // Running a pass afterwards produces its own result and no lock at all.
    const { judge } = makeSpyJudge([]);
    const later = runContradictionPass({ answers: ANSWERS, judge });
    expect(later.conflicts).toHaveLength(0);
    expect("locked" in later).toBe(false);
    expect("lock" in later).toBe(false);
  });
});

describe("ac-31 clause 3: conflict-list entries are pointers into real answer records", () => {
  test("each entry carries >=2 answer-record id references and all of them resolve", () => {
    const list = buildConflictList({ reports: [PAIR_1_2, PAIR_3_4], answers: ANSWERS });
    expect(list).toHaveLength(2);
    for (const entry of list) {
      expect(entry.answer_ids.length).toBeGreaterThanOrEqual(2);
      for (const id of entry.answer_ids) {
        expect(ANSWERS.some((a) => a.id === id)).toBe(true);
      }
    }
  });

  test("entries are pointers, not prose copies of the answers", () => {
    const list = buildConflictList({ reports: [PAIR_1_2], answers: ANSWERS });
    const serialized = JSON.stringify(list);
    expect(serialized).toContain("ans-1");
    expect(serialized).toContain("ans-2");
    expect(serialized).not.toContain(ANSWER_TEXT_AUTO);
    expect(serialized).not.toContain(ANSWER_TEXT_CONFIRM);
  });

  test("an entry pointing at a non-existent answer record is deterministically rejected", () => {
    expect(() =>
      buildConflictList({ reports: [{ answer_ids: ["ans-1", "ans-ghost"] }], answers: ANSWERS }),
    ).toThrow(/ans-ghost/);
  });

  test("an entry with fewer than two pointers cannot form a conflict pair and is rejected", () => {
    expect(() =>
      buildConflictList({ reports: [{ answer_ids: ["ans-1"] }], answers: ANSWERS }),
    ).toThrow(/ans-1/);
  });

  test("the pass output itself is a pointer list: ids resolve, no prose, >=2 pointers per entry", () => {
    const { judge } = makeSpyJudge([PAIR_1_2, PAIR_3_4]);
    const outcome = enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge });
    const conflicts = outcome.pass?.conflicts ?? [];
    expect(conflicts).toHaveLength(2);
    for (const entry of conflicts) {
      expect(entry.answer_ids.length).toBeGreaterThanOrEqual(2);
      for (const id of entry.answer_ids) {
        expect(ANSWERS.some((a) => a.id === id)).toBe(true);
      }
    }
    const serialized = JSON.stringify(conflicts);
    expect(serialized).toContain("ans-1");
    expect(serialized).toContain("ans-4");
    expect(serialized).not.toContain(ANSWER_TEXT_AUTO);
    expect(serialized).not.toContain(ANSWER_TEXT_KEEP);
  });

  test("the pass rejects a judge that reports a ghost pointer — no unvalidated pass-through", () => {
    const ghost = () => [{ answer_ids: ["ans-2", "ans-ghost"] }];
    expect(() => runContradictionPass({ answers: ANSWERS, judge: ghost })).toThrow(/ans-ghost/);
    // Same rejection on the real lock path: the pass cannot launder a ghost.
    expect(() => enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge: ghost })).toThrow(
      /ans-ghost/,
    );
    // Deterministic: the second call rejects exactly as the first.
    expect(() => runContradictionPass({ answers: ANSWERS, judge: ghost })).toThrow(/ans-ghost/);
  });

  test("the pass rejects a judge that reports a single-pointer entry", () => {
    const single = () => [{ answer_ids: ["ans-3"] }];
    expect(() => runContradictionPass({ answers: ANSWERS, judge: single })).toThrow(/ans-3/);
    expect(() => enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge: single })).toThrow(
      /ans-3/,
    );
  });
});

describe("ac-31 clause 4: the conflict count replaces the A4 `conflicting` input (not a constant)", () => {
  test("conflicting equals the conflict-list length: 2 -> 2, 3 -> 3, 0 -> 0", () => {
    const two = runContradictionPass({
      answers: ANSWERS,
      judge: makeSpyJudge([PAIR_1_2, PAIR_3_4]).judge,
    });
    const three = runContradictionPass({
      answers: ANSWERS,
      judge: makeSpyJudge([PAIR_1_2, PAIR_3_4, PAIR_1_4]).judge,
    });
    const zero = runContradictionPass({ answers: ANSWERS, judge: makeSpyJudge([]).judge });

    const fromTwo = deriveConflictingInput(two);
    expect(fromTwo.status).toBe("ran");
    expect(fromTwo.conflicting).toBe(2);

    const fromThree = deriveConflictingInput(three);
    expect(fromThree.conflicting).toBe(3);

    const fromZero = deriveConflictingInput(zero);
    expect(fromZero.status).toBe("ran");
    expect(fromZero.conflicting).toBe(0);
  });

  test("the lock-path record carries the pass-derived count on every run, blocked or not", () => {
    // The record produced by the lock path — the one the floor consumes — must
    // vary with the pass result, on the blocked runs too. A constant literal in
    // the lock path fails at 2 and 3.
    const zero = enterLockPath({
      statement: STATEMENT,
      answers: ANSWERS,
      judge: makeSpyJudge([]).judge,
    });
    const two = enterLockPath({
      statement: STATEMENT,
      answers: ANSWERS,
      judge: makeSpyJudge([PAIR_1_2, PAIR_3_4]).judge,
    });
    const three = enterLockPath({
      statement: STATEMENT,
      answers: ANSWERS,
      judge: makeSpyJudge([PAIR_1_2, PAIR_3_4, PAIR_1_4]).judge,
    });

    expect(zero.record.consistency).toEqual({ status: "ran", conflicting: 0 });
    expect(two.record.consistency).toEqual({ status: "ran", conflicting: 2 });
    expect(three.record.consistency).toEqual({ status: "ran", conflicting: 3 });
    // Each record's count is exactly this run's conflict-list length.
    expect(two.record.consistency.conflicting).toBe(two.pass?.conflicts.length);
    expect(three.record.consistency.conflicting).toBe(three.pass?.conflicts.length);
  });

  test("the lock output embeds that same consistency record, not a re-declared literal", () => {
    const { judge } = makeSpyJudge([]);
    const outcome = enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge });
    expect(outcome.locked).toBe(true);
    // Identity, not just equal shape: the lock carries the very record the
    // pass produced, so `{ status: "ran", conflicting: 0 }` cannot be pasted
    // into the lock branch independently of the pass.
    expect(outcome.lock?.consistency).toBe(outcome.record.consistency);
    expect(outcome.lock?.consistency.conflicting).toBe(outcome.pass?.conflicts.length);
  });
});

describe("ac-31 clause 5: the readiness floor is effectuated by the conflict count", () => {
  test("a pass yielding n>0 conflicts makes the floor actually block the lock", () => {
    const { judge } = makeSpyJudge([PAIR_1_2]);
    const outcome = enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge });
    expect(outcome.locked).toBe(false);
    expect(outcome.lock).toBeUndefined();
    expect(outcome.journal.some((e) => e.kind === "lock")).toBe(false);
    // Blocked for the conflict reason, not the not-run reason.
    expect(outcome.refusal?.reason).toBe("conflicting-floor-blocked");
    expect(outcome.record.consistency).toEqual({ status: "ran", conflicting: 1 });
  });

  test("floor component: conflicting>0 blocks, ran-with-zero passes (no dead constant 0)", () => {
    const conflicted = evaluateConflictingFloor({ status: "ran", conflicting: 2 });
    expect(conflicted.blocked).toBe(true);
    expect(conflicted.reason).toBe("conflicting-floor-blocked");
    const clean = evaluateConflictingFloor({ status: "ran", conflicting: 0 });
    expect(clean.blocked).toBe(false);
    expect(clean.reason).toBeUndefined();
  });

  test("after a clean pass the conflicting component passes the floor and the lock proceeds", () => {
    const { judge } = makeSpyJudge([]);
    const outcome = enterLockPath({ statement: STATEMENT, answers: ANSWERS, judge });
    expect(outcome.locked).toBe(true);
    expect(outcome.journal.some((e) => e.kind === "lock")).toBe(true);
    expect(outcome.refusal).toBeUndefined();
  });
});

describe("ac-31 clause 6: a not-run pass is recorded honestly (ADR-0018), never disguised as verified 0", () => {
  test("the real lock path, reached without running the pass, leaves an explicit not-run marker", () => {
    const outcome = enterLockPath({ statement: STATEMENT, answers: ANSWERS });
    // Same field, same code path as the ran case above — no test-only door.
    expect(outcome.record.consistency).toEqual({ status: "not-run" });
    expect(outcome.locked).toBe(false);
    expect(outcome.journal.some((e) => e.kind === "contradiction-pass")).toBe(false);
  });

  test("not-run and ran-with-zero are deterministically distinguishable in the records", () => {
    const notRun = enterLockPath({ statement: STATEMENT, answers: ANSWERS });
    const ranZero = enterLockPath({
      statement: STATEMENT,
      answers: ANSWERS,
      judge: makeSpyJudge([]).judge,
    });

    expect(ranZero.record.consistency.status).toBe("ran");
    expect(ranZero.record.consistency.conflicting).toBe(0);
    expect(notRun.record.consistency.status).toBe("not-run");
    // The not-run marker must not smuggle in a verified-looking count.
    expect("conflicting" in notRun.record.consistency).toBe(false);
    expect(JSON.stringify(notRun.record.consistency)).not.toBe(
      JSON.stringify(ranZero.record.consistency),
    );
  });

  test("the floor treats not-run fail-closed, with a reason distinct from a conflict block", () => {
    const notRunInput = deriveConflictingInput({ status: "not-run" });
    expect(notRunInput.status).toBe("not-run");
    expect(notRunInput.conflicting).toBeUndefined();
    const verdict = evaluateConflictingFloor(notRunInput);
    expect(verdict.blocked).toBe(true);
    expect(verdict.reason).toBe("consistency-pass-not-run");
  });
});
